Fix MCLPaginator._currentAmount being None in populate()
Without this, I was seeing the error below in the logs and the page for
a certain TV show was unusable. It wouldn't show a cursor and I couldn't
select any season.

```
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```